#!/usr/bin/env python3
"""Embed fonts + CSS mask textures as data URIs (css/inline.css).

Chrome fetches @font-face and CSS mask-image in CORS mode, which fails when
the presentation is opened straight from disk (file://). Inlining them makes
index.html work by double-click with no server.
"""
import base64, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
F = os.path.join(ROOT, "assets", "fonts")
fonts = [("Anton", "Anton-Regular.ttf", "400"), ("Special Elite", "SpecialElite-Regular.ttf", "400"),
         ("Caveat", "Caveat-Variable.ttf", "400 700"), ("Permanent Marker", "PermanentMarker-Regular.ttf", "400"),
         ("Oswald", "Oswald-Variable.ttf", "200 700"), ("IBM Plex Mono", "IBMPlexMono-Regular.ttf", "400")]
def b64(p): return base64.b64encode(open(p, "rb").read()).decode()
out = ["/* generated by tools/inline_assets.py — do not edit */"]
for fam, fn, w in fonts:
    out.append(f"@font-face{{font-family:'{fam}';src:url(data:font/ttf;base64,{b64(os.path.join(F, fn))}) format('truetype');font-weight:{w};font-display:block}}")
g = os.path.join(ROOT, "assets", "textures", "grunge_mask.png")
out.append(f":root{{--grunge:url(data:image/png;base64,{b64(g)})}}")
open(os.path.join(ROOT, "css", "inline.css"), "w").write("\n".join(out) + "\n")
print("css/inline.css", os.path.getsize(os.path.join(ROOT, "css", "inline.css")) // 1024, "KB")
